// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using payroll_service.Data;

#nullable disable

namespace payroll_service.Migrations
{
    [DbContext(typeof(PayrollDbContext))]
    [Migration("20260619032612_AddDependentCount")]
    partial class AddDependentCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("payroll_service.Models.Payroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("base_salary");

                    b.Property<decimal>("BhtnEmployee")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("bhtn_employee");

                    b.Property<decimal>("BhtnEmployer")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("bhtn_employer");

                    b.Property<decimal>("BhxhEmployee")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("bhxh_employee");

                    b.Property<decimal>("BhxhEmployer")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("bhxh_employer");

                    b.Property<decimal>("BhytEmployee")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("bhyt_employee");

                    b.Property<decimal>("BhytEmployer")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("bhyt_employer");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("bonus");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Deduction")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("deduction");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("department_name");

                    b.Property<int>("DependentCount")
                        .HasColumnType("INT")
                        .HasColumnName("dependent_count");

                    b.Property<decimal>("DependentDeduction")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("dependent_deduction");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("employee_id");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("employee_name");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EmployeeName"), "utf8mb4");

                    b.Property<decimal>("FinalSalary")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("final_salary");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("full_name");

                    b.Property<decimal>("GrossIncome")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("gross_income");

                    b.Property<int>("LeaveDays")
                        .HasColumnType("INT")
                        .HasColumnName("leave_days");

                    b.Property<decimal>("OvertimePay")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("overtime_pay");

                    b.Property<decimal>("PersonalTax")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("personal_tax");

                    b.Property<decimal>("TaxableIncome")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("taxable_income");

                    b.Property<decimal>("TotalDeduction")
                        .HasColumnType("DECIMAL(12,2)")
                        .HasColumnName("total_deduction");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("INT")
                        .HasColumnName("working_days");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EmployeeId");

                    b.ToTable("payrolls");
                });
#pragma warning restore 612, 618
        }
    }
}
